# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20160307_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tests.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tests.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.Theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='tests.Course'),
        ),
    ]
